sudo: false
cache: bundler
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_4.0.4.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_edge.gemfile
env:
before_install:
  - gem install bundler --version 1.11.2
script: "bundle exec rake spec"
matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.1.8
      gemfile: gemfiles/rails_edge.gemfile
  allow_failures:
    - gemfile: gemfiles/rails_edge.gemfile
    - rvm: 1.9.3
