sudo: false
cache:
  - bundler
  - directories:
    - vendor/bundle
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
gemfile:
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_edge.gemfile
before_install:
  - gem install bundler --version 1.11.2
  - export BUNDLE_PATH="${TRAVIS_BUILD_DIR}/vendor/bundle"
before_cache:
  - rm -f ${BUNDLE_PATH}/**/extensions/**/{gem_make.out,mkmf.log}
script:
 - bundle exec rake spec
 - script/integration.sh
matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.1.8
      gemfile: gemfiles/rails_edge.gemfile
  allow_failures:
    - rvm: 1.9.3
