sudo: false
cache:
  - bundler
  - directories:
    - vendor/bundle
language: ruby
rvm:
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
gemfile:
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_edge.gemfile
before_install:
  - gem install bundler --version 1.11.2
  - export BUNDLE_PATH="${TRAVIS_BUILD_DIR}/vendor/bundle"
before_cache:
  - rm -f ${BUNDLE_PATH}/**/extensions/**/{gem_make.out,mkmf.log}
script:
 - bundle exec rake spec
 - script/integration.sh
matrix:
  exclude:
    - rvm: 2.1.10
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: 2.4.3
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: 2.4.3
      gemfile: gemfiles/rails_4.2.gemfile
    - rvm: 2.5.0
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: 2.5.0
      gemfile: gemfiles/rails_4.2.gemfile
  allow_failures:
    - gemfile: gemfiles/rails_edge.gemfile
