sudo: false
cache: bundler
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0
gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_4.0.4.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_edge.gemfile
env:
  - DEFER_GC=false RAILS_EDGE=true
before_install:
  - gem install bundler --version 1.11.2
script: "bundle exec rake spec"
matrix:
  allow_failures:
    - rvm: 1.9.3
      gemfile: gemfiles/rails_edge.gemfile
      env: DEFER_GC=false RAILS_EDGE=true
    - rvm: 2.0.0
      gemfile: gemfiles/rails_edge.gemfile
      env: DEFER_GC=false RAILS_EDGE=true
    - rvm: 2.1
      gemfile: gemfiles/rails_edge.gemfile
      env: DEFER_GC=false RAILS_EDGE=true
    - rvm: 2.2
      gemfile: gemfiles/rails_edge.gemfile
      env: DEFER_GC=false RAILS_EDGE=true
    - rvm: 2.3.0
      gemfile: gemfiles/rails_edge.gemfile
      env: DEFER_GC=false RAILS_EDGE=true
